version: "3.9"
services:
  puzzle0:
    build: puzzle0
    networks:
      static-network:
        ipv4_address: 172.16.10.10
  puzzle1_server:
    build: puzzle1_server
    networks:
      static-network:
        ipv4_address: 172.16.10.20
  puzzle1:
    build: puzzle1
    networks:
      static-network:
        ipv4_address: 172.16.10.30
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.16.10.0/24
