version: "3.9"
services:
  puzzle0:
    build: puzzle0
    networks:
      static-network:
        ipv4_address: 172.16.10.10
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.16.10.0/24
